### ISSUE TITLE
Navbar에 있는 마이페이지 클릭 후 /mypage 로 라우팅이 제대로 되지 않는 현상 발생

### ISSUE THREAD

**Issue by luckyjek** [FE-DeLight/wedding-invitation#18]
![image](https://user-images.githubusercontent.com/70943889/230109664-6ff47a7b-faf2-4931-9168-9180839604b4.png)

**Comment by luckyjek** [comment]
마이페이지 경로로 안갔던 이유는 eunkyung 만들어 놓은 폴더 mypage 랑 kyongah 만들어 놓은 mypage.tsx가 있었는데, kyongah mypage.tsx가 먼저 읽혀서 마이페이지 경로가 안나왔던 것이다.

**Comment by KyongAhSeo** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ넵 제 코드를 은경매니저님 페이지로 옮기면 될거같아요!!
