### ISSUE TITLE
연락처 정보 데이터 바인딩

### ISSUE THREAD

**Issue by luckyjek** [FE-DeLight/wedding-invitation#26]
redux 도입 전, 각각 useState를 이용해서 하려고하는데 현재는 아래 형식의 데이터를 사용하고있는데요.
const [contacts, setContacts] = useState([{ id: 1, group: '', title: '', name: '', phone: '' }]);
select되는 선택값이 contacts의 데이터와 어떤식으로 바인딩 해줘야 될지 모르겠습니다.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/70943889/232701972-52173984-cee1-487c-baa5-20b94f7716e0.png">

**Comment by in-kim** [comment]
onChange 이벤트 발생했을때 setContacts에 값을 지정해주면 되지 않을까요?
